export const themes = [
    "conocer a tus suegros", "aprender a manejar", "ir al supermercado", "primera cita", 
    "trabajo en equipo", "dormir en casa ajena", "corte de pelo desastroso", "reunión familiar", 
    "perder el autobús", "presentación en público", "olvidar una contraseña", "día de mudanza", 
    "viaje en avión", "hacer ejercicio en el gimnasio", "despedida de soltero/a", 
    "limpiar la casa", "ir al médico", "hacer una videollamada", "ser el nuevo en el trabajo", 
    "tener una mascota", "pedir comida a domicilio", "ser atrapado en la lluvia", 
    "tener una entrevista de trabajo", "ir al banco", "primer día de clases", 
    "llamada de ventas telefónica", "encontrar a un amigo en la calle", 
    "subir al elevador con desconocidos", "fiesta sorpresa", "perder las llaves", 
    "hablar en sueños", "cita con el dentista", "encontrar dinero en la calle", 
    "comprar ropa online", "usar transporte público", "día de playa", 
    "reunión de exalumnos", "hacer trámites", "encontrar una oferta irresistible", 
    "hacer una devolución", "estar atrapado en el tráfico", "llegar tarde al trabajo", 
    "saludar a alguien que no recuerdas", "confundir a gemelos", "ver una película de terror", 
    "hacer una broma que nadie entiende", "enviar un mensaje al destinatario equivocado", 
    "cita a ciegas", "pedir una pizza", "despertarse tarde", "buscar un cargador", 
    "responder automáticamente a un 'te amo'", "recibir visitas inesperadas", "arreglar el internet", 
    "probar una nueva receta", "hacer limpieza de primavera", "regalar algo usado sin querer", 
    "tratar de reparar algo que no entiendes", "recibir una llamada de un número desconocido"
];
